### ISSUE TITLE
the software keeps closing

### ISSUE THREAD

**Issue by Liger0** [xmrig/xmrig#2409]
**Describe the bug**
The software keeps closing, after a bunch of minutes. No crash, no hang, straight crash.
I use a ryzen 5 1600 and wanted to give it a try. I set it up to only use the gpu so I can eventually mine with the gpu at the same time on a different currency and software.
The CPU is stock, I did test both CPU and RAM and they are totally stable, the CPU during the mining never went above 70°C.
It's the same if I mine with gpu or not while it closes. If I GPU mine the gpu keeps going fine, without hang, crash, driver errors etc.
Other software that I use while mining also go fine.

**To Reproduce**
I just let it run for some minutes...

**Expected behavior**
It shouldn't close

**Required data**
 - Miner log as text or screenshot -> How do I make a log???
 - Config file or command line (without wallets)
[config.zip](https://github.com/xmrig/xmrig/files/6541887/config.zip)

 - OS: [e.g. Windows] Windows 10
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by SChernykh** [comment]
It's explained in **Faulty first gen Zen CPUs** sectio of https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
Try to disable Opcache in BIOS.

**Comment by Liger0** [comment]
I'll try to find it in the bios and report back. Thank you.
Is it the problem that was in the early versions of Ryzen 5 1600? I heard the first months AMD swapped them under warranty, but the later months they were fixed by factory (I'm not talking about the AF version).
In such case my cpu was produced the second half of the factoring year so it's weird.

**Comment by Liger0** [comment]
> 
> 
> It's explained in **Faulty first gen Zen CPUs** section of https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide
> Try to disable Opcache in BIOS.

I disabled it, now the hashrate is constant on 3000 H/s instead of the previous 15000 H/s, is it normal?

**Comment by SChernykh** [comment]
https://xmrig.com/benchmark?cpu=AMD+Ryzen+5+1600+Six-Core+Processor
Disabled opcache reduces hashrate, but you should still get ~4000 h/s with huge pages enabled. 15000 h/s is impossible on that CPU unless you're mining some other coin.

**Comment by Liger0** [comment]
My bad, but it was 4500 H/s before.
