### ISSUE TITLE
Solo Mining Zephyr Gives Error: job error: "Invalid block template received from daemon.

### ISSUE THREAD

**Issue by downystreet** [xmrig/xmrig#3355]
**Describe the bug**
Starting xmrig with "algo": "rx/0", "coin": "Zephyr", and "Daemon": True in the config.json file gives error job error: "Invalid block template received from daemon

**Expected behavior**
xmrig should start solo mining zephyr from daemon

xmrig version: 6.20.0
Tried with zephyr protocol version 1.0.3 and 1.0.4.

**Comment by SChernykh** [comment]
#3356 should fix it.

**Comment by Anaphylaxis** [comment]
same error on 6.20.1-dev
`24.199.101.125:17767 job error: "Invalid block template received from daemon."` This is remote-node.zephyrprotocol.com
```
.\xmrig.exe --version
XMRig 6.20.1-dev
 built on Nov 15 2023 with MSVC 2022
 features: 64-bit AES

libuv/1.44.2
OpenSSL/1.1.1s
hwloc/2.9.0
```

**Comment by SChernykh** [comment]
It works with local node. I wouldn't recommend using remote nodes for solo mining, they can be under high load.

**Comment by Anaphylaxis** [comment]
I compiled zephyrd from github and ran that on my local server, I got the same error after bootstrap.

**Comment by SChernykh** [comment]
> remote node creates miner reward transaction with 3 outputs instead of 2, and XMRig thinks it's invalid. 3rd output is probably the fee taken by that remote node. I'll fix it, but I still recommend to use your own node.

#3358 should fix it.

**Comment by Anaphylaxis** [comment]
> > remote node creates miner reward transaction with 3 outputs instead of 2, and XMRig thinks it's invalid. 3rd output is probably the fee taken by that remote node. I'll fix it, but I still recommend to use your own node.
> 
> #3358 should fix it.

sorry, I still receive `job error: "Invalid block template received from daemon."` with both remote-node.zephyrprotocol.com and my own node using zephyrd 1.0.4
There is no local node on Windows afaik. May install cryptonote-pool and create a 0% pool for myself

**Comment by SChernykh** [comment]
@Anaphylaxis I've been mining for 20 minutes and it didn't give any errors: https://paste.debian.net/hidden/4ef29c32/
Zephyr network mined multiple blocks with 3 outputs in the miner tx during that time. I can't reproduce your issue anymore - maybe you're just not using the latest code.

**Comment by Anaphylaxis** [comment]
@SChernykh strange, i cloned again, checked out to dev, built again, and same error with both nodes. 
https://paste.debian.net/hidden/c2897054/

**Comment by Anaphylaxis** [comment]
It works with "--coin Zephyr". It does not work when I specify -a rx/0

**Comment by rrboston39** [comment]
i dont know how?

**Comment by Anaphylaxis** [comment]
> > It works with "--coin Zephyr". It does not work when I specify -a rx/0. Perhaps rx/0 is monero only and coin is mandatory? Either way I'll keep using --coin from now. Thank you for your persistence and the fix
> 
> @Anaphylaxis Because [#3558](https://github.com/SChernykh/xmrig/blob/0b59b7eb430fb843bbc37dced8f14625d91057f3/src/base/tools/cryptonote/BlockTemplate.cpp#L228-L232) implementation applied the multi output ignore only if the coin is ZEPHYR.

I understand. This feels like an oversight/issue since pool mining works fine with rx/0

**Comment by SChernykh** [comment]
Pool mining leaves this job to the pool, and XMRig just receives the standard block hashing blob which is the same for Monero and Zephyr. But solo mining block template format is different for Zephyr, which is why it doesn't work with rx/0 in command line (rx/0 defaults to Monero).
